<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ctm</string>
	</array>
	<key>name</key>
	<string>CTM</string>
  <key>comment</key><string>CTM Syntax: version 1.0 by Thomas Efer, TextMate version by Benjamin Bock</string>
  <key>keyEquivalent</key><string>^~C</string>
  <key>patterns</key><array>
  	<dict>
  		<key>begin</key><string>#\(</string>
  		<key>end</key><string>\)#</string>
  		<key>name</key><string>comment.block</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%encoding\s+(?=(".+"|""".+""")\s*$).*</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%version\s+(?=\S+\s*$).*</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%prefix\s+\w+\s+(&lt;[^&gt;]+&gt;)</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%prefix\s+\w+\s+([a-zA-Z]+[a-zA-Z0-9+-.]*[:]\/\/([;.)]*[^\s;\].()]+)+)</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%include\s+(&lt;[^&gt;]+>)</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%include\s+([a-zA-Z]+[a-zA-Z0-9+-.]*[:]\/\/([;.)]*[^\s;\].()]+)+)</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%(mergemap|include|ctm).*$</string>
  		<key>name</key><string>comment.line.preprocessor</string>
  	</dict>
  	<dict>
  		<key>match</key><string>#[^\xA\xD]*</string>
  		<key>name</key><string>comment.line.number-sign</string>
  	</dict>
  	<dict>
  		<key>match</key><string>(?&lt;=&lt;)[^&gt;]+(?=&gt;)</string>
  		<key>name</key><string>markup.underline.link</string>
  	</dict>
  	<dict>
  		<key>match</key><string>[a-zA-Z]+[a-zA-Z0-9+-.]*[:]\/\/([;.)]*[^\s;\].()]+)+</string>
  		<key>name</key><string>markup.underline.link</string>
  	</dict>
  	<dict>
  		<key>begin</key><string>"""("{0,2})</string>
  		<key>end</key><string>(?&lt;!""")"""(?!")</string>
  		<key>name</key><string>string.quoted.triple</string>
  	</dict>
  	<dict>
  		<key>begin</key><string>"</string>
  		<key>end</key><string>"</string>
  		<key>name</key><string>string.quoted.double</string>
  	</dict>
  	<dict>
  		<key>match</key><string>(isa|ako|instance-of|def|end)</string>
  		<key>name</key><string>keyword.control.ctm</string>
  	</dict>
  	<dict>
  		<key>match</key><string>iko</string>
  		<key>name</key><string>invalid.deprecated</string>
  	</dict>
  	<dict>
  		<key>match</key><string>\b\w+:[\w_-]+</string>
  		<key>name</key><string>entity.name</string>
  	</dict>
  	<dict>
  		<key>match</key><string>[$]\w+</string>
  		<key>name</key><string>variable.parameter</string>
  	</dict>
  	<dict>
  		<key>match</key><string>\b[\w_-]+(?=\s*\()</string>
  		<key>name</key><string>support.function</string>
  	</dict>
  	<dict>
  		<key>match</key><string>(?&lt;![.])(\d+[.]?\d*)</string>
  		<key>name</key><string>constant.numeric</string>
  	</dict>
  	<dict>
  		<key>match</key><string>((?&lt;!@)@(?!(\s*@)))|((?&lt;!~)~(?!(\s*~)))|((?&lt;!\^)(\^|\^\^)(?!(\s*\^)))</string>
  		<key>name</key><string>keyword.operator</string>
  	</dict>
  	<dict>
  		<key>match</key><string>((?&lt;![.])[.](?!(\s*[.])))|((?&lt;!,),(?!(\s*,)))|((?&lt;!;);(?!(\s*;)))|((?&lt;!\[)\[(?!(\s*\[)))|((?&lt;!\])\](?!(\s*\])))|((?&lt;!-)-\s(?!(\s*-)))|((?&lt;!\()\((?!(\s*\()))|((?&lt;!\))\)(?!(\s*\))))|((?&lt;!:):(?!(\s*:)))</string>
  		<key>name</key><string>keyword.other</string>
  	</dict>
  	<dict>
  		<key>match</key><string>((?&lt;!\*)\*(?!(\s*\*)))</string>
  		<key>name</key><string>constant.numeric</string>
  	</dict>
  	<dict>
  		<key>match</key><string>%.*</string>
  		<key>name</key><string>invalid.illegal</string>
  	</dict>
  	</array>
    <key>scopeName</key>
    <string>source.ctm</string>
	<key>uuid</key>
	<string>B13E6865-F7B8-49B4-99FB-17C29C958582</string>
</dict>
</plist>
